### ISSUE TITLE
Comments change author and disappear

### ISSUE THREAD

**Issue by adamskalik** [presentator/presentator#123]
Hi there. I just found a bug (in version hosted on presentator.io). Some guest comments change author from guest to me and few of the comments just disappear.

Just check by yourself - id: 11332

I hope it will help you somehow improve this dope product!

Cheers

**Comment by ganigeorgiev** [comment]
@adamskalik Thank you for the feedback, but I wasn't able to reproduce the issue.

Could you verify that the comments you are missing are not marked as resolved?
Resolved comments could be toggled on/off with the "Show resolved comments" checkbox:
![Resolved comments toggle](https://i.imgur.com/O8Gndm7.png)

**Comment by adamskalik** [comment]
@ganigeorgiev Comments works fine (i just thinks there was something wrong, but it was fault of nickname swap as i metioned at the beginning of previous message.

sorry for false alarm

**Comment by adamskalik** [comment]
@ganigeorgiev I mean fine because comments not dissappear but swap authors bug still exist. Please check screen below (which im 100% sure was written by someone else - not me)

https://imgur.com/a/gBmBVyI

projects: 11332
prototypes: 15130
comment id: 35892

**Comment by ganigeorgiev** [comment]
@adamskalik I reproduced the bug - when a project admin mark a comment as resolved or change its position, the comment `from` field was updated with the admin's email.

I added a fix in v2.3.1 release but unfortunately the already swapped records cannot be reverted.
